/**
 * Constantes des permissions du système.
 * Correspondent exactement aux valeurs de l'enum Permission.kt du backend.
 * Utilisées pour le contrôle d'accès côté frontend (affichage conditionnel).
 */
export const Permissions = {
  // Référentiels
  TYPE_ANIMAL_READ    : 'TYPE_ANIMAL_READ',
  TYPE_ANIMAL_WRITE   : 'TYPE_ANIMAL_WRITE',
  TYPE_ALIMENT_READ   : 'TYPE_ALIMENT_READ',
  TYPE_ALIMENT_WRITE  : 'TYPE_ALIMENT_WRITE',
  TYPE_DEPENSE_READ   : 'TYPE_DEPENSE_READ',
  TYPE_DEPENSE_WRITE  : 'TYPE_DEPENSE_WRITE',
  TYPE_VENTE_READ     : 'TYPE_VENTE_READ',
  TYPE_VENTE_WRITE    : 'TYPE_VENTE_WRITE',
  INGREDIENT_READ     : 'INGREDIENT_READ',
  INGREDIENT_WRITE    : 'INGREDIENT_WRITE',
  TRAITEMENT_READ     : 'TRAITEMENT_READ',
  TRAITEMENT_WRITE    : 'TRAITEMENT_WRITE',
  FOURNISSEUR_READ    : 'FOURNISSEUR_READ',
  FOURNISSEUR_WRITE   : 'FOURNISSEUR_WRITE',
  FOURNISSEUR_DELETE  : 'FOURNISSEUR_DELETE',

  // Settings
  SETTINGS_READ             : 'SETTINGS_READ',
  SETTINGS_WRITE            : 'SETTINGS_WRITE',
  SETTINGS_LOGO             : 'SETTINGS_LOGO',
  PARAMETRES_ELEVEUR_READ   : 'PARAMETRES_ELEVEUR_READ',
  PARAMETRES_ELEVEUR_WRITE  : 'PARAMETRES_ELEVEUR_WRITE',

  // Infrastructure
  BATIMENT_READ  : 'BATIMENT_READ',
  BATIMENT_WRITE : 'BATIMENT_WRITE',
  BOX_READ       : 'BOX_READ',
  BOX_WRITE      : 'BOX_WRITE',

  // Animaux
  ANIMAL_READ          : 'ANIMAL_READ',
  ANIMAL_STATS         : 'ANIMAL_STATS',
  ANIMAL_WRITE         : 'ANIMAL_WRITE',
  ANIMAL_DELETE        : 'ANIMAL_DELETE',
  ANIMAL_PHOTO         : 'ANIMAL_PHOTO',
  DEPLACEMENT_READ     : 'DEPLACEMENT_READ',
  DEPLACEMENT_WRITE    : 'DEPLACEMENT_WRITE',
  PESEE_READ           : 'PESEE_READ',
  PESEE_WRITE          : 'PESEE_WRITE',
  REPRODUCTION_READ    : 'REPRODUCTION_READ',
  REPRODUCTION_WRITE   : 'REPRODUCTION_WRITE',
  REPRODUCTION_DELETE  : 'REPRODUCTION_DELETE',
  REPRODUCTION_STATS   : 'REPRODUCTION_STATS',
  REPRODUCTION_ALERTES : 'REPRODUCTION_ALERTES',
  REPRODUCTION_ISSF    : 'REPRODUCTION_ISSF',

  // Santé
  ETAT_SANTE_READ  : 'ETAT_SANTE_READ',
  ETAT_SANTE_WRITE : 'ETAT_SANTE_WRITE',
  ETAT_SANTE_DELETE: 'ETAT_SANTE_DELETE',
  SOIN_READ        : 'SOIN_READ',
  SOIN_WRITE       : 'SOIN_WRITE',
  SOIN_STATS       : 'SOIN_STATS',
  SANTE_BILAN      : 'SANTE_BILAN',

  // Finance — Alimentation
  ALIMENTATION_READ   : 'ALIMENTATION_READ',
  ALIMENTATION_WRITE  : 'ALIMENTATION_WRITE',
  ALIMENTATION_DELETE : 'ALIMENTATION_DELETE',
  ALIMENTATION_STATS  : 'ALIMENTATION_STATS',
  ALIMENTATION_RATION : 'ALIMENTATION_RATION',
  ALIMENTATION_COUT   : 'ALIMENTATION_COUT',

  // Finance — Dépenses & Charges
  DEPENSE_READ  : 'DEPENSE_READ',
  DEPENSE_WRITE : 'DEPENSE_WRITE',
  DEPENSE_DELETE: 'DEPENSE_DELETE',
  CHARGE_READ   : 'CHARGE_READ',
  CHARGE_WRITE  : 'CHARGE_WRITE',
  CHARGE_STATS  : 'CHARGE_STATS',

  // Finance — Ventes
  VENTE_READ   : 'VENTE_READ',
  VENTE_WRITE  : 'VENTE_WRITE',
  VENTE_DELETE : 'VENTE_DELETE',
  FACTURE_READ : 'FACTURE_READ',
  SYNTHESE_READ: 'SYNTHESE_READ',

  // Tâches
  TACHE_READ_OWN  : 'TACHE_READ_OWN',
  TACHE_READ_ALL  : 'TACHE_READ_ALL',
  TACHE_CREATE    : 'TACHE_CREATE',
  TACHE_COMPLETE  : 'TACHE_COMPLETE',
  TACHE_VALIDATE  : 'TACHE_VALIDATE',
  TYPE_TACHE_MANAGE: 'TYPE_TACHE_MANAGE',

  // Administration
  UTILISATEUR_READ  : 'UTILISATEUR_READ',
  UTILISATEUR_WRITE : 'UTILISATEUR_WRITE',
  ROLE_MANAGE       : 'ROLE_MANAGE',
  PERMISSION_MANAGE : 'PERMISSION_MANAGE',
} as const;

export type PermissionType = typeof Permissions[keyof typeof Permissions];
